modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
    config = "freeterraforged-common.mixins.json"

[[mixins]]
    config = "freeterraforged-neoforge.mixins.json"

[[mods]]
    modId="freeterraforged"
    displayName="FreeTerraForged"
    version="0.0.6006"
    authors="dags, Won-Ton, racoonman, psiber, squinch"
    credits="The wider TerraForged community, in all its past and present iterations."
    logoFile="logo.png"
    displayURL="https://github.com/etcodehome/freeterraforged/"
    issueTrackerURL="https://github.com/etcodehome/freeterraforged/issues"
    description="Heavily customizable and feature rich overworld terrain generation options."

[[dependencies.freeterraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freeterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.21.1,)"
	ordering = "NONE"
	side = "BOTH"

# We enforce 3.0.14 because otherwise biome previews break in a non-obvious manner
[[dependencies.freeterraforged]]
    modId = "biolith"
    type = "optional"
    versionRange = "[3.0.14,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.your_mod_id]]
modId = "reterraforged"
type = "incompatible"
reason = "RTF is an ancestor of FTF and as such cannot be used in parallel with it."
versionRange = "*"
ordering = "NONE"
side = "BOTH"