modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
    config = "reterraforged-common.mixins.json"

[[mixins]]
    config = "reterraforged-neoforge.mixins.json"

[[mods]]
    modId="reterraforged"
    displayName="ReTerraForged"
    version="${version}"
    authors="dags,Won-Ton,racoonman2,psiber,squinch"
    credits="raccoonman and the wider TerraForged community, in all its past and present iterations."
    logoFile="logo.png"
    displayURL="https://github.com/raccoonman/reterraforged/"
    issueTrackerURL="https://github.com/raccoonman/reterraforged/issues"
    description="ReTerraForged is a community-driven fork of ReTerraForged for modern Minecraft, providing highly customizable Overworld terrain generation and continuing the TerraForged lineage."

[[dependencies.reterraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.21.1,)"
	ordering = "NONE"
	side = "BOTH"

# We enforce 3.0.14 because otherwise biome previews break in a non-obvious manner
[[dependencies.reterraforged]]
    modId = "biolith"
    type = "optional"
    versionRange = "[3.0.14,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.your_mod_id]]
modId = "reterraforged"
type = "incompatible"
reason = "RTF is an ancestor of RTF and as such cannot be used in parallel with it."
versionRange = "*"
ordering = "NONE"
side = "BOTH"
