modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
    config = "reterraforged-common.mixins.json"

[[mixins]]
    config = "reterraforged-neoforge.mixins.json"

[[mods]]
    modId="reterraforged"
    displayName="ReTerraForged"
    version="0.0.6005"
    authors="dags,Won-Ton,raccoonman,psiber"
    credits="dags,Won-Ton,raccoonman,psiber"
    logoFile="logo.png"
    displayURL="https://github.com/racoonman2/reterraforged/"
    issueTrackerURL="https://github.com/racoonman2/reterraforged/issues"
    description="A continuation of https://github.com/TerraForged/TerraForged"

[[dependencies.reterraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.21.1,)"
	ordering = "NONE"
	side = "BOTH"

# We enforce 3.0.14 because otherwise biome previews break in a non-obvious manner
[[dependencies.reterraforged]]
    modId = "biolith"
    type = "optional"
    versionRange = "[3.0.14,)"
    ordering = "AFTER"
    side = "BOTH"